export const REPOSITORY_TOKENS = {
  CLIENT_REPOSITORY: 'CLIENT_REPOSITORY',
  CONTACT_REPOSITORY: 'CONTACT_REPOSITORY',
  DEAL_REPOSITORY: 'DEAL_REPOSITORY',
  TASK_REPOSITORY: 'TASK_REPOSITORY',
  USER_REPOSITORY: 'USER_REPOSITORY',
} as const;

export const SERVICE_TOKENS = {
  CLIENT_SERVICE: 'CLIENT_SERVICE',
  CONTACT_SERVICE: 'CONTACT_SERVICE',
  DEAL_SERVICE: 'DEAL_SERVICE',
  TASK_SERVICE: 'TASK_SERVICE',
  USER_SERVICE: 'USER_SERVICE',
  EMAIL_SERVICE: 'EMAIL_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
} as const;

export const HANDLER_TOKENS = {
  CREATE_CLIENT_HANDLER: 'CREATE_CLIENT_HANDLER',
  UPDATE_CLIENT_HANDLER: 'UPDATE_CLIENT_HANDLER',
  DELETE_CLIENT_HANDLER: 'DELETE_CLIENT_HANDLER',
  GET_CLIENT_HANDLER: 'GET_CLIENT_HANDLER',
  GET_CLIENTS_HANDLER: 'GET_CLIENTS_HANDLER',
  CREATE_CONTACT_HANDLER: 'CREATE_CONTACT_HANDLER',
  UPDATE_CONTACT_HANDLER: 'UPDATE_CONTACT_HANDLER',
  DELETE_CONTACT_HANDLER: 'DELETE_CONTACT_HANDLER',
  GET_CONTACT_HANDLER: 'GET_CONTACT_HANDLER',
  GET_CONTACTS_HANDLER: 'GET_CONTACTS_HANDLER',
  CREATE_DEAL_HANDLER: 'CREATE_DEAL_HANDLER',
  UPDATE_DEAL_HANDLER: 'UPDATE_DEAL_HANDLER',
  DELETE_DEAL_HANDLER: 'DELETE_DEAL_HANDLER',
  GET_DEAL_HANDLER: 'GET_DEAL_HANDLER',
  GET_DEALS_HANDLER: 'GET_DEALS_HANDLER',
} as const; 